#!/usr/bin/env bash
# Displays DNS information for a given domain and subdomain.

display_info() {
    local domain=$1
    local subdomain=$2

    record=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print}')
    record_type=$(echo "$record" | awk '{print $4}')
    destination=$(echo "$record" | awk '{print $5}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 1 ]; then
    display_info "$1" "www"
    display_info "$1" "lb-01"
    display_info "$1" "web-01"
    display_info "$1" "web-02"
else
    display_info "$1" "$2"
fi
